//! The lockfile — `project.lock` (`docs/23` §7).
//!
//! The lockfile pins the *exact* version, source, and content hash of every
//! resolved package. "Lockfile is truth, manifest is constraint": a build reads
//! the lockfile and resolves the graph against it, only mutating it when the
//! manifest demands a change. The `sha256` is verified on every fetch and
//! extraction — a mismatch is a hard error, never a silent re-download.
//!
//! The file is generated; it is not hand-edited. Serialization is deterministic
//! (packages sorted by `(name, version, source)`).

use std::fmt;

use serde::{Deserialize, Serialize};

/// The current lockfile format version (`docs/23` §7 excerpt shows `4`).
pub const LOCKFILE_VERSION: u32 = 4;

/// A parsed `project.lock`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Lockfile {
    pub version: u32,
    /// Resolved packages, kept sorted by `(name, version, source)` for determinism.
    pub packages: Vec<LockedPackage>,
}

/// One pinned package in the lockfile.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LockedPackage {
    pub name: String,
    pub version: String,
    pub source: LockSource,
    /// `sha256:<hex>` content hash. Registry/git sources carry one; path deps
    /// do not (they are not content-addressed).
    pub checksum: Option<String>,
}

/// The pinned source of a locked package, encoded as the lockfile `source`
/// string (`registry+<index>`, `path+<path>`, `git+<url>#<rev>`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum LockSource {
    Registry { index: String },
    Path { path: String },
    Git { url: String, rev: String },
}

impl LockSource {
    /// The lockfile `source =` string for this source.
    pub fn encode(&self) -> String {
        match self {
            LockSource::Registry { index } => format!("registry+{index}"),
            LockSource::Path { path } => format!("path+{path}"),
            LockSource::Git { url, rev } => format!("git+{url}#{rev}"),
        }
    }

    /// Parse a lockfile `source =` string.
    pub fn decode(s: &str) -> Result<LockSource, LockError> {
        if let Some(rest) = s.strip_prefix("registry+") {
            Ok(LockSource::Registry {
                index: rest.to_string(),
            })
        } else if let Some(rest) = s.strip_prefix("path+") {
            Ok(LockSource::Path {
                path: rest.to_string(),
            })
        } else if let Some(rest) = s.strip_prefix("git+") {
            let (url, rev) = rest.split_once('#').ok_or_else(|| {
                LockError::Parse(format!("git source `{rest}` is missing a `#<rev>` pin"))
            })?;
            Ok(LockSource::Git {
                url: url.to_string(),
                rev: rev.to_string(),
            })
        } else {
            Err(LockError::Parse(format!("unknown source form `{s}`")))
        }
    }
}

/// Why a lockfile could not be parsed.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum LockError {
    Toml(String),
    Parse(String),
}

impl fmt::Display for LockError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            LockError::Toml(m) => write!(f, "invalid lockfile: {m}"),
            LockError::Parse(m) => write!(f, "invalid lockfile: {m}"),
        }
    }
}

impl std::error::Error for LockError {}

impl Lockfile {
    /// An empty lockfile at the current version.
    pub fn empty() -> Lockfile {
        Lockfile {
            version: LOCKFILE_VERSION,
            packages: Vec::new(),
        }
    }

    /// Parse a `project.lock` from its text.
    pub fn parse(text: &str) -> Result<Lockfile, LockError> {
        let raw: RawLock =
            toml::from_str(text).map_err(|e| LockError::Toml(e.message().to_string()))?;
        let mut packages = Vec::new();
        for p in raw.package {
            packages.push(LockedPackage {
                name: p.name,
                version: p.version,
                source: LockSource::decode(&p.source)?,
                checksum: p.checksum,
            });
        }
        let mut lock = Lockfile {
            version: raw.version,
            packages,
        };
        lock.sort();
        Ok(lock)
    }

    /// Serialize to deterministic TOML text.
    pub fn to_toml(&self) -> String {
        let mut out = String::new();
        out.push_str("# This file is generated by otter_fusion; do not edit.\n");
        out.push_str(&format!("version = {}\n", self.version));
        let mut packages = self.packages.clone();
        packages.sort_by(|a, b| {
            (&a.name, &a.version, a.source.encode()).cmp(&(&b.name, &b.version, b.source.encode()))
        });
        for p in &packages {
            out.push_str("\n[[package]]\n");
            out.push_str(&format!("name     = {}\n", toml_str(&p.name)));
            out.push_str(&format!("version  = {}\n", toml_str(&p.version)));
            out.push_str(&format!("source   = {}\n", toml_str(&p.source.encode())));
            if let Some(c) = &p.checksum {
                out.push_str(&format!("checksum = {}\n", toml_str(c)));
            }
        }
        out
    }

    fn sort(&mut self) {
        self.packages.sort_by(|a, b| {
            (&a.name, &a.version, a.source.encode()).cmp(&(&b.name, &b.version, b.source.encode()))
        });
    }

    /// Look up a locked package by name.
    pub fn get(&self, name: &str) -> Option<&LockedPackage> {
        self.packages.iter().find(|p| p.name == name)
    }
}

/// Quote a string as a TOML basic string.
fn toml_str(s: &str) -> String {
    let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

// --- serde shapes -----------------------------------------------------------

#[derive(Deserialize, Serialize)]
struct RawLock {
    #[serde(default = "default_version")]
    version: u32,
    #[serde(default)]
    package: Vec<RawLockPackage>,
}

fn default_version() -> u32 {
    LOCKFILE_VERSION
}

#[derive(Deserialize, Serialize)]
struct RawLockPackage {
    name: String,
    version: String,
    source: String,
    #[serde(default)]
    checksum: Option<String>,
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"
version = 4

[[package]]
name     = "serde"
version  = "1.2.7"
source   = "registry+https://pkgs.example.dev/index"
checksum = "sha256:9f8bc41a"

[[package]]
name     = "foo-local"
version  = "0.1.0"
source   = "path+../foo"

[[package]]
name     = "bar-git"
version  = "0.4.0"
source   = "git+https://example.com/bar#abc123"
"#;

    #[test]
    fn parses_all_three_source_forms() {
        let lock = Lockfile::parse(SAMPLE).unwrap();
        assert_eq!(lock.version, 4);
        assert_eq!(lock.packages.len(), 3);
        // Sorted by name: bar-git, foo-local, serde.
        assert_eq!(lock.packages[0].name, "bar-git");
        assert_eq!(
            lock.packages[0].source,
            LockSource::Git {
                url: "https://example.com/bar".into(),
                rev: "abc123".into()
            }
        );
        assert_eq!(
            lock.get("foo-local").unwrap().source,
            LockSource::Path {
                path: "../foo".into()
            }
        );
        assert_eq!(
            lock.get("serde").unwrap().source,
            LockSource::Registry {
                index: "https://pkgs.example.dev/index".into()
            }
        );
        assert_eq!(
            lock.get("serde").unwrap().checksum.as_deref(),
            Some("sha256:9f8bc41a")
        );
        assert!(lock.get("foo-local").unwrap().checksum.is_none());
    }

    #[test]
    fn round_trips_through_toml() {
        let lock = Lockfile::parse(SAMPLE).unwrap();
        let text = lock.to_toml();
        let reparsed = Lockfile::parse(&text).unwrap();
        assert_eq!(lock, reparsed);
    }

    #[test]
    fn serialization_is_deterministic_and_sorted() {
        let mut lock = Lockfile::empty();
        lock.packages.push(LockedPackage {
            name: "zed".into(),
            version: "1.0.0".into(),
            source: LockSource::Path {
                path: "../zed".into(),
            },
            checksum: None,
        });
        lock.packages.push(LockedPackage {
            name: "alpha".into(),
            version: "2.0.0".into(),
            source: LockSource::Registry {
                index: "https://r".into(),
            },
            checksum: Some("sha256:ff".into()),
        });
        let a = lock.to_toml();
        let b = lock.to_toml();
        assert_eq!(a, b);
        // `alpha` must serialize before `zed`.
        assert!(a.find("alpha").unwrap() < a.find("zed").unwrap());
    }

    #[test]
    fn git_source_without_rev_is_an_error() {
        assert!(matches!(
            LockSource::decode("git+https://x"),
            Err(LockError::Parse(_))
        ));
    }

    #[test]
    fn unknown_source_form_is_an_error() {
        assert!(matches!(
            LockSource::decode("svn+https://x"),
            Err(LockError::Parse(_))
        ));
    }
}
