[package]
name = "cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "otter_fusion"
path = "src/main.rs"

[dependencies]
compiler.workspace = true
backend = { path = "../backend" }
clap = { version = "4", features = ["derive"] }
